# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoP', models.CharField(max_length=50)),
                ('apellidoM', models.CharField(max_length=50)),
                ('edad', models.PositiveSmallIntegerField()),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
