# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0002_auto_20170623_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellidoM',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
